sonar.exclusions=\
  **/*.d.ts,\
  **/app/**,\
  **/components/ui/**,\
  **/components/auth/ParticleNetwork.tsx,\
  **/lib/**,\
  **/features/*/presentation/pages/**,\
  **/features/*/presentation/components/**,\
  **/features/*/presentation/index.ts,\
  **/backend/src/auth/infrastructure/strategies/**,\
  **/main.ts,\
  **/app.module.ts