sonar.sources=frontend/src,backend/src

sonar.tests=frontend/tests,backend/test

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.exclusions=\
**/*.d.ts,\
**/app/**,\
**/components/ui/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info