{
 "title": "k6 Load Testing Results",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the InfluxDB exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting"
   }
  ]
 },
 "panels": [
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active VUs",
     "query": "SELECT max(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Requests per Second",
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Failed",
     "query": "SELECT max(\"value\") FROM \"http_req_failed\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_check",
     "query": "SELECT sum(\"value\") FROM \"checks\" WHERE $timeFilter GROUP BY time($__interval), \"check\" fill(none)"
    }
   ]
  },
  {
   "title": "$Measurement (mean)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM http_req_duration WHERE $timeFilter and value > 0"
    }
   ]
  },
  {
   "title": "$Measurement (max)",
   "type": "stat",
   "gridPos": { "x": 4, "y": 8, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT max(\"value\") FROM http_req_duration WHERE $timeFilter and value > 0"
    }
   ]
  },
  {
   "title": "$Measurement (med)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 8, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT median(\"value\") FROM http_req_duration WHERE $timeFilter and value > 0"
    }
   ]
  },
  {
   "title": "$Measurement (min)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT min(\"value\") FROM http_req_duration WHERE $timeFilter and value > 0"
    }
   ]
  },
  {
   "title": "$Measurement (p90)",
   "type": "stat",
   "gridPos": { "x": 16, "y": 8, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT percentile(\"value\", 90) FROM http_req_duration WHERE $timeFilter and value > 0"
    }
   ]
  },
  {
   "title": "$Measurement (p95)",
   "type": "stat",
   "gridPos": { "x": 20, "y": 8, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT percentile(\"value\", 95) FROM http_req_duration WHERE $timeFilter and value > 0"
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "timeseries",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "max",
     "query": "SELECT max(\"value\") FROM http_req_duration WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "p95",
     "query": "SELECT percentile(\"value\", 95) FROM http_req_duration WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "p90",
     "query": "SELECT percentile(\"value\", 90) FROM http_req_duration WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "min",
     "query": "SELECT min(\"value\") FROM http_req_duration WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "heatmap",
   "gridPos": { "x": 12, "y": 11, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM http_req_duration WHERE $timeFilter and value > 0"
    }
   ]
  }
 ]
}